version: "3.9"

services:
  db:
    build: .
    restart: unless-stopped
    env_file: .env               # переменные окружения
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./initdb:/docker-entrypoint-initdb.d:ro  # если хотите монтить скрипты напрямую

volumes:
  pgdata:
