-- engine_rw (DDL + RW)
CREATE ROLE engine_rw LOGIN PASSWORD '${ENGINE_DB_PASS}';
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO engine_rw;
GRANT ALL ON ALL TABLES IN SCHEMA public TO engine_rw;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO engine_rw;

-- teams_ro (только SELECT)
CREATE ROLE teams_ro LOGIN PASSWORD '${READER_DB_PASS}';
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO teams_ro;
GRANT USAGE ON SCHEMA public TO teams_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO teams_ro;