version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sport-db
    restart: unless-stopped
    environment:
      POSTGRES_DB:       sport
      POSTGRES_USER:     user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sport"]
      interval: 10s
      retries: 5
    ports:
      - "5432:5432"

  service-a:
    build: ./service-a
    container_name: service-a
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      service-b:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL:      jdbc:postgresql://postgres:5432/sport
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      OTHER_SERVICE_URL:         http://service-b:8080
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8080/ping || exit 1"]
      interval: 30s
      retries: 5

  service-b:
    build: ./service-b
    container_name: service-b
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL:      jdbc:postgresql://postgres:5432/sport
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8080/ping || exit 1"]
      interval: 30s
      retries: 5

volumes:
  pgdata:
